openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8082
  description: Generated server url
paths:
  /api/v1/calculate:
    post:
      tags:
      - calculate-api-controller
      summary: Calcula la suma de dos números con un porcentaje dinámico
      operationId: calculateSumWithPercentage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalculateBody"
        required: true
      responses:
        "200":
          description: Cálculo exitoso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CalculateResult"
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "429":
          description: Demasiadas solicitudes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/v1/history:
    get:
      tags:
      - history-api-controller
      summary: Obtiene el historial de llamadas a la API
      operationId: getHistory
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: string
          default: "0"
      - name: size
        in: query
        required: false
        schema:
          type: string
          default: "10"
      responses:
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "200":
          description: Historial recuperado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedHistory"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "204":
          description: Sin datos para la solicitud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedHistory"
        "429":
          description: Demasiadas solicitudes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    CalculateBody:
      type: object
      properties:
        num1:
          type: number
          format: double
          example: 5
        num2:
          type: number
          format: double
          example: 5
    CalculateResult:
      type: object
      properties:
        result:
          type: number
          format: double
          example: 11
    Error:
      type: object
      properties:
        code:
          type: number
          example: 429
        message:
          type: string
          example: Solicitudes por minuto superadas
    HistoryRecord:
      type: object
      properties:
        date:
          type: string
          format: date-time
        requestMethod:
          type: string
        requestEndpoint:
          type: string
        requestParams:
          type: string
        requestBody:
          type: string
          description: cuerpo de petición serializada como string
        responseStatus:
          type: integer
          format: int32
        responseBody:
          type: string
          description: cuerpo de respuesta serializada como string
    PaginatedHistory:
      type: object
      properties:
        total:
          type: integer
          format: int64
        records:
          type: array
          items:
            $ref: "#/components/schemas/HistoryRecord"
